class StallTracker:
    def __init__(self, name: str, relevant_thread: int): ...
    def go_active(self) -> None: ...
    def go_idle(self) -> None: ...
    def is_active(self) -> bool: ...
    def counter_address(self) -> int: ...

def stall_gil(seconds: float) -> None: ...
